######################################################################
# Automatically generated by qmake (3.0) ?? 2? 27 21:46:48 2017
######################################################################

TEMPLATE = app
TARGET = show
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += widgets
