######################################################################
# Automatically generated by qmake (3.0) ?? 2? 27 23:25:37 2017
######################################################################

TEMPLATE = app
TARGET = show
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += widgets
