######################################################################
# Automatically generated by qmake (3.0) ?? 2? 27 20:29:01 2017
######################################################################

TEMPLATE = app
TARGET = show
INCLUDEPATH += .

# Input
SOURCES += main.cpp
